//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderConfirmed
    {
        public int Id { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string CustomerId { get; set; }
        public string OrderName { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        public string PaymentMode { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DeliveryUpto { get; set; }
        public Nullable<System.DateTime> DeliveredDate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Product Product { get; set; }
    }
}
