//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public OrderDetail()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int OrderDetailsId { get; set; }
        public string CustomerName { get; set; }
        public string DeliveryAddress { get; set; }
        public string CustomerMobile { get; set; }
        public System.DateTime OrderDate { get; set; }
        public Nullable<System.DateTime> OrderConfirmedDate { get; set; }
        public string PaymentMode { get; set; }
        public Nullable<System.DateTime> OrderDeliveryDate { get; set; }
        public Nullable<System.DateTime> OrderExcpectedDelivery { get; set; }
        public string Size { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
    }
}
